#!/usr/bin/env bash
# Generate `moved` blocks for a zone whose record addresses have changed.
#
# Record keys carry a hash of the value, and TXT records live in their own
# resource. Upgrading across a key change therefore reads as destroy+create for
# every record. That is survivable for an A record and an outage for MX and the
# SPF/DKIM/DMARC TXT records, so the moves are worth making explicit.
#
# Matching is done on what the records *are* — zone, type, name, content,
# priority — read from state, never by recomputing an old key format. There
# have been several, including fixed keys for the generated records, and a
# wrong reconstruction would move a record onto the wrong address.
#
# Output is a `moved.tf` in the zone directory: the moves then show up in a
# normal plan, get reviewed in a pull request, and apply through the usual
# pipeline. Delete the file once applied.
#
# Usage:
#   plan-state-moves.sh <zone>
#
# Testing hooks (skip Terragrunt, feed fixtures instead):
#   STATE_JSON_FILE=… PLAN_JSON_FILE=… plan-state-moves.sh <zone>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ZONE="${1:?Usage: plan-state-moves.sh <zone>}"
ZONE_DIR="${REPO_ROOT}/envs/cloudflare/zones/${ZONE}"
MOVED_FILE="${ZONE_DIR}/moved.tf"

[ -d "$ZONE_DIR" ] || error_exit 1 "Zone directory not found: ${ZONE_DIR}"

if [ -n "${STATE_JSON_FILE:-}" ] && [ -n "${PLAN_JSON_FILE:-}" ]; then
  state_json="$(cat "$STATE_JSON_FILE")"
  plan_json="$(cat "$PLAN_JSON_FILE")"
else
  log_info "Reading current state for ${ZONE}..."
  state_json="$(cd "$ZONE_DIR" && terragrunt run --log-disable -- show -json)"

  log_info "Planning ${ZONE} to resolve the new addresses..."
  plan_file="${ZONE_DIR}/tfplan.moves"
  # Absolute -out: Terragrunt runs OpenTofu/Terraform inside .terragrunt-cache.
  (cd "$ZONE_DIR" && terragrunt plan -out="$plan_file" --non-interactive >/dev/null)
  plan_json="$(cd "$ZONE_DIR" && terragrunt run --log-disable -- show -json "$plan_file")"
  rm -f "$plan_file"
fi

report="$(
  jq -n \
    --argjson state "$state_json" \
    --argjson plan "$plan_json" '
    # Every resource object in the state, at any module depth.
    def resources($doc):
      [$doc.values?.root_module? | .. | objects | select(has("address") and has("type") and has("values"))];

    (resources($state) | map(select(.type == "cloudflare_zone"))
      | map({ (.values.id | tostring): .values.name }) | add // {}) as $zone_names
    |
    (resources($state) | map(select(.type == "cloudflare_dns_record"))) as $current
    |
    (($plan.planned_values?.outputs?.dns_records?.value) // {}
      | to_entries
      | map({
          key: .key,
          domain: .value.domain,
          resource: .value.resource,
          type: .value.type,
          # State stores names as FQDNs; configuration uses relative names.
          fqdn: (if .value.name == "@" then .value.domain else "\(.value.name).\(.value.domain)" end),
          value: .value.value,
          priority: (.value.priority // 0),
        })) as $desired
    |
    $current
    | map(
        . as $cur
        | ($zone_names[$cur.values.zone_id | tostring] // null) as $domain
        | ($desired | map(select(
            .domain == $domain
            and .type == $cur.values.type
            and .fqdn == $cur.values.name
            and .value == $cur.values.content
            and .priority == (($cur.values.priority // 0))
          ))) as $exact
        | (if ($exact | length) == 1 then $exact[0] else null end) as $match
        | {
            from: $cur.address,
            to: (if $match == null then null
                 else "module.dns_zone.\($match.resource)[\"\($match.key)\"]" end),
            domain: $domain,
            record: "\($cur.values.type) \($cur.values.name)",
            matched: ($match != null),
          }
      )
    | {
        total: length,
        moves: map(select(.matched and .from != .to)),
        # In state but not in the configuration: these are destroyed on apply.
        orphans: map(select(.matched | not) | "\(.domain // "?"): \(.record)"),
      }
  '
)"

moves="$(jq '.moves' <<<"$report")"
count="$(jq '.moves | length' <<<"$report")"
total="$(jq '.total' <<<"$report")"
orphan_count="$(jq '.orphans | length' <<<"$report")"

if [ "$orphan_count" -gt 0 ]; then
  log_warning "${orphan_count} record(s) in state have no counterpart in the configuration and will be destroyed:"
  jq -r '.orphans[] | "    \(.)"' <<<"$report" >&2
fi

if [ "$count" -eq 0 ]; then
  log_success "No address changes for ${ZONE}: state already matches the current key scheme."
  rm -f "$MOVED_FILE"
  exit 0
fi

{
  echo "# Generated by .github/scripts/plan-state-moves.sh — review, apply, then delete."
  echo "#"
  echo "# Each block moves one record from the address it has in state to the"
  echo "# address the current configuration gives it. Without these, the next"
  echo "# apply destroys and recreates the record, which for MX and the"
  echo "# SPF/DKIM/DMARC TXT records means a gap in mail delivery."
  echo
  jq -r '.[] | "# \(.domain): \(.record)\nmoved {\n  from = \(.from)\n  to   = \(.to)\n}\n"' <<<"$moves"
} >"$MOVED_FILE"

terraform fmt "$MOVED_FILE" >/dev/null 2>&1 || true

log_warning "${count} of ${total} records change address — wrote ${MOVED_FILE#"${REPO_ROOT}/"}"
log_info "Review it, run a plan (the moves appear as \"has moved to\"), apply, then delete the file."
