#!/usr/bin/env bash
# Move every zone lock file to the newest provider its constraint allows.
#
# Dependabot cannot do this: it only rewrites a lock when it also changes a
# version in a manifest, and 5.23.0 already satisfies "~> 5.0". The manifests
# here are generated by Terragrunt at runtime and never committed, so a scanner
# looking for .tf files next to the lock finds nothing either.
#
# Outputs (via GITHUB_OUTPUT when set):
#   changed  - "true" | "false"
#   summary  - one line per zone whose provider version moved

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ZONES_DIR="${REPO_ROOT}/envs/cloudflare/zones"

# Hashes are per platform: CI is linux, laptops are darwin. A lock missing the
# CI platform fails init on the runner.
PLATFORMS=(-platform=linux_amd64 -platform=darwin_amd64 -platform=darwin_arm64)

# No remote state needed to resolve providers, and a fork has no TFC org.
export TG_BACKEND=local
export CLOUDFLARE_ACCOUNT_ID="${CLOUDFLARE_ACCOUNT_ID:-00000000000000000000000000000000}"

locked_version() {
  sed -n 's/^[[:space:]]*version[[:space:]]*=[[:space:]]*"\(.*\)"/\1/p' "$1" | head -1
}

summary=""

for dir in "${ZONES_DIR}"/*/; do
  zone="$(basename "$dir")"
  lock="${dir}.terraform.lock.hcl"

  grep -qE '^\s*"[^"]+"\s*=' "${dir}variables.auto.tfvars" 2>/dev/null || continue

  before="—"
  [ -f "$lock" ] && before="$(locked_version "$lock")"

  log_info "Refreshing ${zone} (locked: ${before})..."
  (
    cd "$dir"
    terragrunt init -backend=false -upgrade --non-interactive >/dev/null
    # Through Terragrunt, not terraform directly: Terragrunt copies the unit
    # into .terragrunt-cache and generates the .tf files there, so a bare
    # `terraform providers lock` here runs against an empty directory, silently
    # locks nothing, and leaves whatever `init` recorded for the runner's own
    # platform. Output is left visible -- hiding it is what kept that quiet.
    terragrunt run -- providers lock "${PLATFORMS[@]}"
  )

  # A lock that covers only the platform that generated it is the failure this
  # step is here to prevent, and it looks exactly like success. Count instead.
  h1_count="$(grep -c '"h1:' "$lock" || true)"
  if [ "$h1_count" -ne "${#PLATFORMS[@]}" ]; then
    log_error "${zone}: lock has ${h1_count} h1 hashes, expected ${#PLATFORMS[@]} (one per platform)"
    exit 1
  fi

  after="$(locked_version "$lock")"
  if [ "$before" != "$after" ]; then
    log_warning "${zone}: ${before} → ${after}"
    summary="${summary}- \`${zone}\`: ${before} → ${after}"$'\n'
  else
    log_info "${zone}: unchanged (${after})"
  fi
done

# Hash-only churn without a version change is noise; ignore it.
if [ -z "$summary" ]; then
  log_success "All zone locks already on the newest allowed provider."
  git -C "$REPO_ROOT" checkout -- "envs/cloudflare/zones" 2>/dev/null || true
  changed=false
else
  changed=true
fi

if [ -n "${GITHUB_OUTPUT:-}" ]; then
  echo "changed=${changed}" >>"$GITHUB_OUTPUT"
  {
    echo "summary<<EOF"
    printf '%s' "$summary"
    echo "EOF"
  } >>"$GITHUB_OUTPUT"
fi
